# Generated by Django 4.0.3 on 2023-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=1000)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
