# Generated by Django 4.0.3 on 2023-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0002_acc_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('favorite', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('invested', models.CharField(max_length=30)),
            ],
        ),
    ]
