# Generated by Django 4.0.3 on 2023-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0003_favoritestock_investstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('invested', models.CharField(max_length=30)),
                ('shares', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='InvestStock',
        ),
    ]
