# Generated by Django 4.0.3 on 2023-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0004_invested_delete_investstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invested',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
