# Generated by Django 4.0.3 on 2023-04-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0005_invested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invested',
            name='shares',
            field=models.FloatField(default=0.0),
        ),
    ]
