# Generated by Django 4.0.3 on 2023-04-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEx', '0006_alter_invested_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='created',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
